"""empty message

Revision ID: 068d352a0f4b
Revises: f2144e0413a8
Create Date: 2023-10-13 14:32:11.611678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068d352a0f4b'
down_revision = 'f2144e0413a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
